export const NOTE_GET_ALL_LOADING = 'NOTE_GET_ALL_LOADING';
export const NOTE_SET_ALL = 'NOTE_SET_ALL';
export const NOTE_SET_FILTERED = 'NOTE_SET_FILTERED';
export const NOTE_GET_ALL_ERROR = 'NOTE_GET_ALL_ERROR';
export const NOTE_MODAL_SET_DATA = 'NOTE_MODAL_SET_DATA';
export const NOTE_SET_SEARCH = 'NOTE_SET_SEARCH';

export const COMMON_SET_TITLE = 'COMMON_SET_TITLE';
export const COMMON_SET_BIG_LOADER = 'COMMON_SET_BIG_LOADER';

