export const NOTE_GET_ALL_LOADING = `NOTE_GET_ALL_LOADING`;
export const NOTE_SET_ALL = `NOTE_SET_ALL`;
export const NOTE_SET_FILTERED = `NOTE_SET_FILTERED`;
export const NOTE_MODAL_SET_DATA = `NOTE_MODAL_SET_DATA`;
export const NOTE_SET_SEARCH = `NOTE_SET_SEARCH`;
export const NOTE_SHOW_COMPLETED = `NOTE_SHOW_COMPLETED`;

export const COMMON_SET_TITLE = `COMMON_SET_TITLE`;
export const COMMON_SET_BIG_LOADER = `COMMON_SET_BIG_LOADER`;

export const AUTH_SET_TOKEN = `AUTH_SET_TOKEN`;
